version: '3.4'
services:
  nanj:
    image: web-api
    build: ./
    command: bash -c "ln -fs /node_modules /app/node_modules; npm run build; node index.js"
    volumes:
      - ./:/app
    ports:
      - 8088:8088
