version: '3.4'
services:
  web-api:
    image: web-api
    build: ./
    command: bash -c "ln -s /node_modules /app/node_modules; node index.js"
    volumes:
      - ./:/app
    ports:
      - 8088:8088
